# infra/06-app-python.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-python-svc
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend-python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-python
  template:
    metadata:
      labels:
        app: backend-python
    spec:
      containers:
        - name: backend-python
          image: trading-manage-app/backend-python:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets