apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-python
  template:
    metadata:
      labels:
        app: backend-python
    spec:
      containers:
        - name: backend-python
          image: your-registry/tbill-backend-python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Kafka (추가)
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "tbill-python-group"
            
            # Redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-python-svc
spec:
  selector:
    app: backend-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
