apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-java
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
        - name: backend-java
          image: your-registry/tbill-backend-java:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # PostgreSQL
            - name: DB_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_POSTGRES_HOST
            - name: DB_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_POSTGRES_PORT
            - name: DB_POSTGRES_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_POSTGRES_DBNAME
            - name: DB_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            
            # Redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            
            # Kafka (추가)
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_CONSUMER_GROUP_ID
            
            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            
            # Spring Profile
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-java-svc
spec:
  selector:
    app: backend-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
