apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  POSTGRES_PASSWORD: "1234"
  JWT_SECRET: "c3ByaW5nLXNlY3VyaXR5LWp3dC10dXRvcmlhbC1zZWNyZXQtYmFzZTY0LWtleS1mb3ItamF2YS1kZXZlbG9wZXJzLXRiaWxsCg=="
  REDIS_PASSWORD: "1234"